import React from 'react';
import estilo from "../estilos/terminos.module.css";
import Footer from "../components/Footer";
import logo from "../images/Bristol-01.svg";

function Terminos() {
  return (
    <>
     <div className={estilo.App}>
      <header className={estilo.AppHeader}>
        <img className={estilo.imglogo} src={logo} width={150} alt="Logo Bristol"/>
        <h1>Terminos y Condiciones</h1></header>
          <h3 className={estilo.sub}>1. Premio </h3>
          <p>Al ingresar y utilizar este portal de Internet, cuyo nombre de dominio es www.bristol.com propiedad de Bristol S.A. de C.V., que en lo sucesivo se denominará Bristol S.A. de C.V., el usuario está aceptando los TÉRMINOS Y CONDICIONES DE USO contenidos en este convenio y declara expresamente su aceptación utilizando para tal efecto medios electrónicos, en términos de lo dispuesto por el artículo 1803 del Código Civil Federal. 
            En caso de no aceptar en forma absoluta y completa los términos y condiciones de este convenio, el usuario deberá abstenerse de acceder, utilizar y observar el sitio web www.ilusion.com
            Y en caso de que el usuario acceda, utilice y observe el sitio web www.bristol.com se considerará como una absoluta y expresa aceptación de los TÉRMINOS Y CONDICIONES DE USO aquí estipulados.
            La sola tilización de dicha página de Internet le otorga al público en general la condición de usuario (en adelante referido como el «usuario» o los «usuarios») e implica la aceptación, plena e incondicional, de todas y cada una de las condiciones generales y particulares incluidas en estos TÉRMINOS Y CONDICIONES DE USO publicados por Bristol S.A. de C.V. en el momento mismo en que el usuario acceda al sitio web.
            Cualquier modificación a los presentes TÉRMINOS Y CONDICIONES DE USO será realizada cuando el titular de la misma, en este caso cuando Bristol S.A. de C.V. lo considere apropiado, siendo exclusiva responsabilidad del usuario asegurarse de tomar conocimiento de tales modificaciones.</p>
          <h3 className={estilo.sub}>2. Convenio</h3>
          <p>Convenio de adhesión para el uso de la página de Internet www.bristol.com nbsp;que celebran: por una parte, Bristol S.A. de C.V. y, por la otra, el usuario, sujetándose, ambas partes, a lo establecido en este documento.</p>
          <h3 className={estilo.sub}>3. Licencia</h3>
          <p>Por virtud de la celebración de este convenio, Bristol S.A. de C.V. otorga y concede al usuario el derecho no exclusivo, revocable y no transferible de ver y utilizar el sitio web www.bristol.com de conformidad con los TÉRMINOS Y CONDICIONES DE USO que aquí se estipulan. Para los efectos del presente convenio, las partes acuerdan que por «usuario» se entenderá a cualquier persona de cualquier naturaleza que ingrese al sitio web www.bristol.com y/o a cualquiera de las subpáginas que despliegan su contenido y/o a la persona de cualquier naturaleza que se dé de alta y/o use cualquiera de los servicios que se ofrecen a través de dicha página. 
           El usuario sólo podrá imprimir y/o copiar cualquier información contenida o publicada en el sitio web www.bristol.com exclusivamente para uso personal, queda terminantemente prohibido el uso comercial de dicha información. En caso de ser persona moral se sujetará a lo dispuesto por el artículo 148, fracción IV de la Ley Federal del Derecho de Autor. 
           La reimpresión, publicación, distribución, asignación, sublicencia, venta, reproducción electrónica o por otro medio, parcial o total, de cualquier información, documento o gráfico que aparezca en el sitio web www.bristol.com para cualquier uso distinto al personal no comercial le está expresamente prohibido al usuario, a menos de que cuente con la autorización previa y por escrito de Bristol S.A. de C.V.</p>
          <h3 className={estilo.sub}>4. Reglas para el uso del sitio web www.bristol.com </h3>
          <p> El usuario y Bristol S.A. de C.V. están de acuerdo en que la utilización del sitio web www.bristol.com se sujetará a las siguientes reglas:/
            Información contenida en el sitio web www.ilusion.com. El usuario reconoce y acepta que la información publicada o contenida en dicho sitio será claramente identificada de forma tal que se reconozca que la misma proviene y ha sido generada por Bristol S.A. de C.V. o por sus proveedores.
            No obstante, la información, conceptos y opiniones publicadas en dicho sitio no necesariamente reflejan la posición de Bristol S.A. de C.V. , ni de sus empleados, oficiales, directores, accionistas, licenciatarios y concesionarios (en lo sucesivo los «afiliados»). Por esta razón, Bristol S.A. de C.V. no se hace responsable por ninguna de las informaciones, opiniones y conceptos que se emitan en la página web referida. En este caso, se recomienda al usuario consultar con un especialista y/o profesional en la materia. Asimismo, Bristol S.A. de C.V. no se hace responsable de la información contenida en la página de Internet, incluidas las subpáginas, en el entendido de que el uso y seguimiento de la misma es bajo riesgo y responsabilidad del usuario.
            Bristol S.A. de C.V. se reserva el derecho de bloquear el acceso o remover en forma parcial o total toda información, comunicación o material que a su exclusivo juicio pueda resultar: i) abusivo, difamatorio u obsceno; ii) fraudulento, artificioso o engañoso; iii) violatorio de derechos de autor, marcas, confidencialidad, secretos industriales o cualquier derecho de propiedad intelectual de un tercero; iv) ofensivo o; v) que de cualquier forma contravenga lo establecido en este convenio. Si el usuario desea obtener mayor información de un tema en específico proveído por Bristol S.A. de C.V. o sus proveedores deberá consultarlo directamente con cada uno de ellos, según corresponda, y/o con un especialista en la materia.
            El usuario reconoce que Bristol S.A. de C.V. controla o censura previamente el contenido disponible en la página de Internet. Por tal motivo, Bristol S.A. de C.V. no asume ninguna responsabilidad por el contenido provisto a dicha página por proveedores independientes o ajenos a Bristol S.A. de C.V. y no tiene el control editorial sobre el contenido, información y/o material generado y/o provisto por terceros. Todas las opiniones, consejos, declaraciones, servicios, ofertas u otras informaciones o contenidos expresados o puestos a disposición del público por terceros, pertenecen a su respectivo autor y Bristol S.A. de C.V. no asume responsabilidad alguna frente a ello. De la misma forma, Bristol S.A. de C.V. no garantiza la exactitud, veracidad, amplitud y/o utilidad de cualquier contenido provisto por tales terceros. Adicionalmente, Bristol S.A. de C.V. no es responsable ni garantiza la exactitud, exhaustividad, veracidad y/o confiabilidad de cualquier opinión, información, consejo o declaración expresados por Bristol S.A. de C.V. a través de su página de Internet y bajo ninguna circunstancia Bisrol S.A. de C.V. será responsable de cualquier daño y/o perjuicio, directo o indirecto, causado en virtud de la confianza que el usuario deposite en información obtenida a través de su sitio web. Bristol S.A. de C.V. se reserva el derecho de suprimir o modificar el contenido de esta página que, a exclusivo juicio de Bristol S.A. de C.V. no cumpla con sus estándares o que pudiera resultar contrario al ordenamiento jurídico vigente y, por consiguiente, no será responsable por cualquier falla o tardanza que se genere al eliminar tal material.</p>
          <h3 className={estilo.sub}>5. Formatos</h3>
          <p>Los usuarios reconocen que, al proporcionar la información de carácter personal requerida en alguno de los servicios que se prestan en este sitio web, otorgan a Diltex S.A. de C.V. la autorización señalada en el artículo 109 de la Ley Federal del Derecho de Autor. En todos los casos, los usuarios responderán por la veracidad de la información proporcionada a Bristol S.A. de C.V.
            Asimismo, para la prestación de servicios, el usuario se obliga además a aceptar los términos y condiciones estipulados para tal efecto.</p>
      
    </div>
    <Footer></Footer>
    </>
   
  );
}

export default Terminos;